CREATE TABLE IF NOT EXISTS public.encuesta_capacidades_tecnologicas (
    id bigint PRIMARY KEY NOT NULL,
    user_id bigint DEFAULT NULL,
    user_type character varying(500) DEFAULT NULL,
    personal_type character varying(50) DEFAULT NULL,
    user_email character varying(500) DEFAULT NULL,
    user_dni character varying(50) DEFAULT NULL,
    user_name character varying(500) DEFAULT NULL,
    user_lastname character varying(500) DEFAULT NULL,
    user_phone character varying(50) DEFAULT NULL,
    code_info character varying(20) DEFAULT NULL,
    info_name character varying(500) DEFAULT NULL,
    user_state character varying(500) DEFAULT NULL,
    user_municipality character varying(500) DEFAULT NULL,
    user_parish character varying(500) DEFAULT NULL,
    user_zone_type character varying(500) DEFAULT NULL,
    user_blender_user_skills character varying(500) DEFAULT NULL,
    user_python_user_skills character varying(500) DEFAULT NULL,
    user_stop_motion_skills character varying(500) DEFAULT NULL,
    user_web_design_skills character varying(500) DEFAULT NULL,
    user_wordpress_skills character varying(500) DEFAULT NULL,
    user_html_skills character varying(500) DEFAULT NULL,
    user_PHP_skills character varying(500) DEFAULT NULL,
    user_blog_design_skills character varying(500) DEFAULT NULL,
    user_digital_magazine_skills character varying(500) DEFAULT NULL,
    user_digital_economy_skills character varying(500) DEFAULT NULL,
    user_crypto_assets_skills character varying(500) DEFAULT NULL,
    user_e_bank_patria_skills character varying(500) DEFAULT NULL,
    user_e_commerce_skills character varying(500) DEFAULT NULL,
    user_use_movile_devices_skills character varying(500) DEFAULT NULL,
    user_technical_support_computers_devices_skills character varying(500) DEFAULT NULL,
    user_technical_support_movile_devices_skills character varying(500) DEFAULT NULL,
    user_network_technical_support_skills character varying(500) DEFAULT NULL,
    user_social_media_management_skills character varying(500) DEFAULT NULL,
    user_social_media_security_skills character varying(500) DEFAULT NULL,
    user_imagen_design_skills character varying(500) DEFAULT NULL,
    user_mobile_video_editing_skills character varying(500) DEFAULT NULL,
    user_remote_communication_skills character varying(500) DEFAULT NULL,
    user_libre_office_applications_skills character varying(500) DEFAULT NULL,
    user_meme_creations_skills character varying(500) DEFAULT NULL,
    user_presentations_creations_skills character varying(500) DEFAULT NULL,
    user_accounting_books_skills character varying(500) DEFAULT NULL,
    user_budget_cration_skills character varying(500) DEFAULT NULL,
    user_strategic_planning_skills character varying(500) DEFAULT NULL,
    user_project_elaboration_skills character varying(500) DEFAULT NULL,
    user_collective_diagnosis_skills character varying(500) DEFAULT NULL,
    user_situational_analysis_tecniques_skills character varying(500) DEFAULT NULL,
    user_systematization_community_experiences_skills character varying(500) DEFAULT NULL,
    user_content_assertive_organizational_communication_skills character varying(500) DEFAULT NULL,
    user_robotics_skills character varying(500) DEFAULT NULL,
    user_artificial_intelligence_skills character varying(500) DEFAULT NULL,
    user_programming_skills character varying(500) DEFAULT NULL,
    user_application_creation_skills character varying(500) DEFAULT NULL,
    user_greater_technological_skill character varying(500) DEFAULT 'N/A',
    user_greater_technological_skill_level character varying(500) DEFAULT 'N/A',
    user_training_needs character varying(500) DEFAULT NULL,
    user_other_training_needs character varying(500) DEFAULT NULL,
    user_know_PNCT_MincCYT character varying(500) DEFAULT NULL,
    user_potential_contribution_for_areas_PNCT character varying(500) DEFAULT NULL,
    user_know_PNI_infocentro character varying(500) DEFAULT NULL,
    user_potential_contribution_for_PNI_infocentro character varying(500) DEFAULT NULL,
    knowledge_remote_learning character varying(500) DEFAULT NULL,
    participation_virtual_training character varying(500) DEFAULT NULL,
    experience_online_training character varying(500) DEFAULT NULL,
    know_platform_aprendiendo_juntos character varying(500) DEFAULT NULL,
    training_received_aprendiendo_juntos character varying(500) DEFAULT NULL,
    interest_to_training_on_aprendiendo_juntos character varying(500) DEFAULT NULL,
    know_benefits_online_training character varying(500) DEFAULT NULL,
    suggestions_provided character varying(500) DEFAULT NULL,
    user_name_os character varying(500) DEFAULT NULL,
    date_reg timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    date_update timestamp with time zone

);
ALTER TABLE public.encuesta_capacidades_tecnologicas OWNER TO lanubede;

CREATE SEQUENCE IF NOT EXISTS public.encuesta_capacidades_tecnologicas_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.encuesta_capacidades_tecnologicas_id_seq OWNER TO lanubede;
ALTER SEQUENCE public.encuesta_capacidades_tecnologicas_id_seq OWNED BY public.encuesta_capacidades_tecnologicas.id;

ALTER TABLE ONLY public.encuesta_capacidades_tecnologicas ALTER COLUMN id SET DEFAULT nextval('public.encuesta_capacidades_tecnologicas_id_seq'::regclass);

-- INSERT INTO public.encuesta_capacidades_tecnologicas(user_name) VALUES('User Demo');